apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: ${{ values.resourceName }}
  description: Azure Web App for ${{ values.resourceName }}
  annotations:
    github.com/project-slug: ${{ values.repoUrl | projectSlug }}
spec:
  type: service
  lifecycle: experimental
  owner: user:guest